# Generated by Django 6.0.3 on 2026-03-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': "Aloqa ma'lumotlari",
                'verbose_name_plural': "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='Yil')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Tajribalar',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('specialty', models.CharField(default='Senior Full-Stack Developer', max_length=150, verbose_name='Mutaxassislik')),
                ('bio', models.TextField(verbose_name='Bio / Haqida')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Rasm')),
                ('years_of_experience', models.PositiveIntegerField(default=5, verbose_name='Tajriba yillari')),
                ('projects_count', models.PositiveIntegerField(default=65, verbose_name='Loyihalar soni')),
                ('work_together_url', models.CharField(blank=True, help_text='Telegram bot yoki email manzilingiz. Masalan: https://t.me/username yoki mailto:email@example.com', max_length=300, verbose_name="'Birga ishlash' tugmasi URL")),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nomi (ko'rsatiladigan)")),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Platforma')),
                ('url', models.URLField(verbose_name='URL manzil')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order'],
            },
        ),
    ]
